comision_remunerada_info:
    path: /comision_remunerada_info
    defaults: {_controller: ComisionRemuneradaBundle:Default:comision_remunerada_info}

solicitudcomisionservicio:
    path: /solicitudcomisionservicio_new
    defaults: {_controller: ComisionRemuneradaBundle:SolicitudComisionServicio:new}

solicitudes_serv_remun:
    path: /solicitudes_serv_remun
    defaults: {_controller: ComisionRemuneradaBundle:AAPP:solicitudes_serv_remun}

estado_sol_prof:
    path: /estado-solicitud
    defaults: {_controller: ComisionRemuneradaBundle:Default:estado_sol_prof}

informe_pdf:
    path: /comision-servicio/informe-pdf
    defaults: {_controller: ComisionRemuneradaBundle:Default:informePDF}


#solicitud_serv_remun:
 #   path: /solicitud_serv_remun
  #  defaults: {_controller: ComisionRemuneradaBundle:Default:solicitud_serv_remun}


#envio_solicitud:
 #   path: /envio_solicitud
  #  defaults: {_controller: ComisionRemuneradaBundle:AAPP:solicitudes_serv_remun}

#descarga_archivo_ajax:
    #path:     /solicitud_serv_remun/envio-solicitud
    #defaults: { _controller: ComisionRemuneradaBundle:Default:descargaArchivo }
    #requirements:
        #_method:  POST
