comision-servicio-informacion:
    path: /comision-servicio/informacion
    defaults: {_controller: ComisionRemuneradaBundle:Default:comisionServicioInfo}

solicitudcomisionservicio_new:
    path: /solicitudcomisionservicio_new/{apr}
    defaults: {_controller: ComisionRemuneradaBundle:SolicitudComisionServicio:new}
    requirements:
            _method:  POST

validador:
    path: /validar-usuario
    defaults: {_controller: ComisionRemuneradaBundle:SolicitudComisionServicio:validador}

comision_servicio_ver_solicitud:
    path: /comision-de-servicio/solicitud/{id}
    defaults: {_controller: ComisionRemuneradaBundle:Default:verSolicitud}

comision-de-servicio-insertar:
    path: /comision-de-servicio/insertar
    defaults: {_controller: ComisionRemuneradaBundle:Default:insertar}

solicitudes-comision-de-servicio:
    path: /comision-de-servicio/solicitudes
    defaults: {_controller: ComisionRemuneradaBundle:Default:solicitudesComisionServicio}

estado_sol_prof:
    path: /comision-de-servicio/estado-solicitud
    defaults: {_controller: ComisionRemuneradaBundle:Default:estado_sol_prof}

informe_pdf:
    path: /comision-servicio/informe-pdf
    defaults: {_controller: ComisionRemuneradaBundle:Default:informePDF}

informe:
    path: /comision-servicio/informe
    defaults: {_controller: ComisionRemuneradaBundle:Default:informe}

comision_servicio_solicitudes_catedra:
    path: /comision-de-servicio/solicitudes
    defaults: {_controller: ComisionRemuneradaBundle:Default:verSolicitudes}

comision-de-servicio-insertar-posible-respuesta:
    path: /comision-de-servicio/insertar-posible-respuesta
        defaults: {_controller: ComisionRemuneradaBundle:Default:insertarPosibleRespuesta}

solicitud_buscarcedula_ajax:
    path:     /solicitud/buscar-cedula
    defaults: { _controller: ComisionRemuneradaBundle:SolicitudComisionServicio:buscarCedulaAjax }
    requirements:
        _method:  POST

solicitud_guardararchivos_ajax:
    path:     /solicitud/guardar-archivos-datos
    defaults: { _controller: ComisionRemuneradaBundle:solicitudcomisionservicio:guardarArchivosAjax }

comision_servicio_solicitudes_facultad:
    path: /comision-de-servicio/solicitudes
    defaults: {_controller: ComisionRemuneradaBundle:Default:verSolicitudesFacultad}

comision_servicio_solicitudes_aapp:
    path: /comision-de-servicio/solicitudes
    defaults: {_controller: ComisionRemuneradaBundle:Default:verSolicitudesAAPP}