comision-servicio-remunerada-info:
    path: /comision-servicio-remunerada-info
    defaults: {_controller: ComisionRemuneradaBundle:Default:comision_remunerada_info}

solicitud_serv_remun:
    path: /solicitud_serv_remun
    defaults: {_controller: ComisionRemuneradaBundle:Default:solicitud_serv_remun}

solicitudes_serv_remun:
    path: /solicitudes_serv_remun
    defaults: {_controller: ComisionRemuneradaBundle:AAPP:solicitudes_serv_remun}