registro_usuario_index: 
    path:     /registro/usuario
    defaults: { _controller: RegistroUnicoBundle:RegistrarUsuario:registrarUsuario }

registro_registeruser_ajax:
    path:     /registro/registrar-usuario
    defaults: { _controller: RegistroUnicoBundle:RegistrarUsuario:registrarUsuarioAjax }
    requirements:
        _method:  POST
        
registro_buscarcedula_ajax:
    path:     /registro/buscar-cedula
    defaults: { _controller: RegistroUnicoBundle:RegistrarUsuario:buscarCedulaAjax }
    requirements:
        _method:  POST
        
registro_datos_index:
    path:     /registro/datos/{apr}
    defaults: { _controller: RegistroUnicoBundle:RegistrarDatos:registrarDatosUsuario }

registro_guardar_ajax:
    path:     /registro/guardar-datos
    defaults: { _controller: RegistroUnicoBundle:RegistrarDatos:guardarDatosAjax }
    requirements:
        _method:  POST

registro_guardararchivos_ajax:
    path:     /registro/guardar-archivos-datos
    defaults: { _controller: RegistroUnicoBundle:RegistrarDatos:guardarArchivosAjax }
    requirements:
        _method:  POST
        
registro_obtener_ajax:
    path:     /registro/obtener-datos
    defaults: { _controller: RegistroUnicoBundle:RegistrarDatos:enviarDataAjax }
    requirements:
        _method:  POST
        
registro_buscaremail_ajax:
    path:     /registro/buscar-email
    defaults: { _controller: RegistroUnicoBundle:RegistrarDatos:buscarEmailAjax }
    requirements:
        _method:  POST
        
registro_obteneremails_ajax:
    path:     /registro/enviar-emails
    defaults: { _controller: RegistroUnicoBundle:RegistrarDatos:enviarEmailsAjax }
    requirements:
        _method:  POST

registro_obtenerlastid_ajax:
    path:    /registro/enviar-lastid
    defaults: { _controller: RegistroUnicoBundle:RegistrarDatos:obtenerIdAjax }
    requirements:
        _method:  POST

registro_consulta_index:
    path:     /registro/consulta
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:consultarRegistro }

registro_consultaobteneremails_ajax:
    path:     /consulta/enviar-emails
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:enviarEmailsAjax }

registro_consultarregistros_ajax:
    path:     /consulta/enviar-registros
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:enviarRegistrosDeUsuarioAjax }

registro_consultarparticipantes_ajax:
    path:     /consulta/enviar-participantes
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:enviarRegistrosDeParticipantesAjax }

registro_consultarrevistas_ajax:
    path:     /consulta/enviar-revistas
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:enviarRegistrosDeRevistasAjax }

registro_consultardatospersonales_ajax:
    path:     /consulta/enviar-datos-personales
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:enviarDatosPersonalesAjax }

registro_consultarcargos_ajax:
    path:     /consulta/enviar-cargos
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:enviarCargosDeUsuarioAjax }

registro_consultarhijos_ajax:
    path:     /consulta/enviar-hijos
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:enviarDatosPersonalesHijosAjax }

registro_consultardocumentshijos_ajax:
    path:     /consulta/enviar-hijos-url
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:enviarDatosPersonalesHijosPathAjax }
    
registro_consultarbuscaremail_ajax:
    path:     /consulta/buscar-email
    defaults: { _controller: RegistroUnicoBundle:ConsultarDatos:buscarEmailAjax }
