preparadores:
    resource: "@PreparadoresBundle/Controller/"
    type:     annotation
    prefix:   /

clausulas_contractuales:
    resource: "@ClausulasContractualesBundle/Resources/config/routing.yml"
    prefix:   /

registro_unico:
    resource: "@RegistroUnicoBundle/Resources/config/routing.yml"
    prefix:   /

plan_septenal:
    resource: "@PlanSeptenalBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
