jubilacion-informacion:
    path: /jubilacion-informacion
    defaults: {_controller: JubilacionBundle::info}

jubilacion-solicitud:
    path: /jubilacion-solicitud
    defaults: {_controller: JubilacionBundle::solicitud}

direccion-asuntos-Prof:
    path: /direccion-asuntos-Prof
    defaults: {_controller: JubilacionBundle::direccion}

consejo-facultad:
    path: /consejo-facultad
    defaults: {_controller: JubilacionBundle::consejo}

constancia-jubilacion:
    path: /constancia-jubilacion
    defaults: {_controller: JubilacionBundle::constanciaJubilacion}

informe-jubilacion:
    path: /informe-jubilacion
    defaults: {_controller: JubilacionBundle::informeJubilacion}

informe-jubilacion-pdf:
    path: /informe-jubilacion-pdf
    defaults: {_controller: JubilacionBundle::informeJubilacionPDF}

codigo-barra:
    path: /codigo-barra
    defaults: {_controller: JubilacionBundle::barcodeImage}