jubilacion-informacion:
    path: /jubilacion-informacion
    defaults: {_controller: JubilacionBundle::info}

jubilacion-solicitud:
    path: /jubilacion-solicitud
    defaults: {_controller: JubilacionBundle::solicitud}

direccion-asuntos-Prof:
    path: /direccion-asuntos-Prof
    defaults: {_controller: JubilacionBundle::direccion}

consejo-facultad:
    path: /consejo-facultad
    defaults: {_controller: JubilacionBundle::consejo}

/jubilacion/informe-jubilacion:
    path: /jubilacion/informe-jubilacion
    defaults: {_controller: JubilacionBundle::informeJubilacion}
    requirements:
        _method: POST|GET

/jubilacion/informe-jubilacion-pdf:
    path: /jubilacion/informe-jubilacion-pdf
    defaults: {_controller: JubilacionBundle::informeJubilacionPDF}
    requirements:
        _method: GET

estado-solicitud:
    path: /estado-solicitud
    defaults: {_controller: JubilacionBundle::progresoSolicitudProf}

revisar-solicitud:
    path: /revisar-solicitud/{id}
    defaults: {_controller: JubilacionBundle::revisarSolicitud}

codigo-barra:
    path: /codigo-barra
    defaults: {_controller: JubilacionBundle::barcodeImage}

insertar:
  path:     /insertar
  defaults: { _controller: JubilacionBundle::insertar }
  requirements:
    _method: POST

llenarPDF:
  path:     /llenarPDF
  defaults: { _controller: JubilacionBundle::llenarPDF }
  requirements:
    _method: GET, POST

revisar-solicitud-consejo:
    path: /revisar-solicitud-consejo/{id}
    defaults: {_controller: JubilacionBundle::revisarSolicitudConsejo}

insertarConsejo:
  path:     /insertar-consejo
  defaults: { _controller: JubilacionBundle::insertarConsejo }
  requirements:
    _method: POST

/jubilacion/informe-jubilacion-consejo:
    path: /jubilacion/informe-jubilacion-consejo
    defaults: {_controller: JubilacionBundle::informeConsejo}
    requirements:
        _method: POST|GET

tramites-atendidos-consejo:
    path: /tramites-atendidos-consejo
    defaults: {_controller: JubilacionBundle::tramitesAtendidosConsejo}

cargar-informe-consejo:
    path: /cargar-informe-consejo
    defaults: {_controller: JubilacionBundle::cargarInformeConsejo}

cargar-informe-direccion:
    path: /cargar-informe-direccion
    defaults: {_controller: JubilacionBundle::cargarInformeDireccion}

/solicitud/guardar-archivos:
  path:     /solicitud/guardar-archivos
  defaults: { _controller: JubilacionBundle:TramiteJubilacion:guardarArchivosAjax }
  requirements:
    _method: GET, POST