RegistroUnicoBundle\Entity\Estatus:
    type: entity
    table: null
    repositoryClass: RegistroUnicoBundle\Repository\EstatusRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            length: '50'
            unique: true
            column: Description
    lifecycleCallbacks: {  }
