RegistroUnicoBundle\Entity\Nivel:
    type: entity
    table: null
    repositoryClass: RegistroUnicoBundle\Repository\NivelRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            length: '50'
            unique: true
    lifecycleCallbacks: {  }
