RegistroUnicoBundle\Entity\Revista:
    type: entity
    table: null
    repositoryClass: RegistroUnicoBundle\Repository\RevistaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            length: '50'
    lifecycleCallbacks: {  }
