services:
    plan_septenal.plan_septenal_individual_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - PlanSeptenalBundle\Entity\PlanSeptenalIndividual
    plan_septenal.plan_septenal_colectivo_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - PlanSeptenalBundle\Entity\PlanSeptenalColectivo
