AppBundle\Entity\Usuario:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UsuarioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        cedula:
            type: string
            length: '25'
        primerNombre:
            type: string
            length: '50'
            column: primer_nombre
        segundoNombre:
            type: string
            length: '50'
            column: segundo_nombre
        primerApellido:
            type: string
            length: '50'
            column: primer_apellido
        segundoApellido:
            type: string
            length: '50'
            column: segundo_apellido
        nacionalidad:
            type: string
            length: '50'
        correo:
            type: string
            length: '50'
        telefono:
            type: integer
        rif:
            type: integer
        fechaNacimiento:
            type: date
            column: fecha_nacimiento
            nullable: true
        fechaFallecimiento:
            type: date
            column: fecha_fallecimiento
            nullable: true
        contraseña:
            type: string
            length: '100'
        activo:
            type: boolean
        rolId:
            type: integer
            column: estatus_id
    lifecycleCallbacks: {  }
